# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Josh McBroom
email: mcbroomjc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  User-Focused Full-Stack Developer
baseurl: "/startbootstrap-freelancer-jekyll" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: JoshuaMcBroom
github_username:  dropTheNon
facebook_username: Josh.McBroom
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://www.linkedin.com/in/joshmcbroom

# Address information
# address_street: 3034 Melrose Place
address_city: Seattle
address_state: WA
address_zip: 98106

# Build settings
markdown: kramdown
